additionalProperties: true
type: object
title: Application Property
description: >
  An application property. It is a caller defined JSON object that Bitbucket
  will store and return. 

  The `_attributes` field at its top level can be used to control who is allowed
  to read and update the property. 

  The keys of the JSON object must match an allowed pattern. For details, 

  see [Application properties](/cloud/bitbucket/application-properties/).
properties:
  _attributes:
    type: array
    items:
      type: string
      enum:
        - public
        - read_only
