allOf:
  - $ref: ./object.yaml
  - additionalProperties: true
    type: object
    title: Deployment Environment
    description: A Bitbucket Deployment Environment.
    properties:
      uuid:
        type: string
        description: The UUID identifying the environment.
      name:
        type: string
        description: The name of the environment.
x-bb-default-fields:
  - uuid
x-bb-url: >-
  /rest/2.0/accounts/{target_user.uuid}/repositories/{repository.uuid}/environments/{uuid}
x-bb-batch-url: >-
  /rest/2.0/accounts/{target_user.uuid}/repositories/{repository.uuid}/environments_batch
x-bb-batch-max-size: 100
