allOf:
  - $ref: ./object.yaml
  - additionalProperties: true
    type: object
    title: Deployment Release
    description: A Bitbucket Deployment Release.
    properties:
      uuid:
        type: string
        description: The UUID identifying the release.
      name:
        type: string
        description: The name of the release.
      url:
        type: string
        format: uri
        description: Link to the pipeline that produced the release.
      commit:
        $ref: ./commit.yaml
      created_on:
        type: string
        format: date-time
        description: The timestamp when the release was created.
