allOf:
  - $ref: ./object.yaml
  - additionalProperties: true
    type: object
    title: Pipelines Configuration
    description: The Pipelines configuration for a repository.
    properties:
      enabled:
        type: boolean
        description: Whether Pipelines is enabled for the repository.
      repository:
        $ref: ./repository.yaml
