allOf:
  - $ref: ./object.yaml
  - type: object
    title: Project
    description: |-
      A Bitbucket project.
                  Projects are used by teams to organize repositories.
    properties:
      links:
        type: object
        properties:
          html:
            type: object
            title: Link
            description: A link to a resource related to this object.
            properties:
              href:
                type: string
                format: uri
              name:
                type: string
            additionalProperties: false
          avatar:
            type: object
            title: Link
            description: A link to a resource related to this object.
            properties:
              href:
                type: string
                format: uri
              name:
                type: string
            additionalProperties: false
        additionalProperties: false
      uuid:
        type: string
        description: The project's immutable id.
      key:
        type: string
        description: The project's key.
      owner:
        $ref: ./team.yaml
      name:
        type: string
        description: The name of the project.
      description:
        type: string
      is_private:
        type: boolean
        description: |-

          Indicates whether the project is publicly accessible, or whether it is
          private to the team and consequently only visible to team members.
          Note that private projects cannot contain public repositories.
      created_on:
        type: string
        format: date-time
      updated_on:
        type: string
        format: date-time
      has_publicly_visible_repos:
        type: boolean
        description: |-

          Indicates whether the project contains publicly visible repositories.
          Note that private projects cannot contain public repositories.
    additionalProperties: true
