get:
  tags:
    - Deployments
  description: Retrieve a deployment
  summary: Get a deployment
  operationId: getDeploymentForRepository
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: deployment_uuid
      description: The deployment UUID.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The deployment.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/deployment.yaml
    '404':
      description: No account, repository or deployment with the UUID provided exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
