get:
  tags:
    - Pipelines
  summary: Get a variable for a repository
  description: Retrieve a repository level variable.
  operationId: getRepositoryPipelineVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: variable_uuid
      description: The UUID of the variable to retrieve.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The variable.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_variable.yaml
    '404':
      description: >-
        The account, repository or variable with the specified UUID was not
        found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
put:
  tags:
    - Pipelines
  summary: Update a variable for a repository
  description: Update a repository level variable.
  operationId: updateRepositoryPipelineVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: variable_uuid
      description: The UUID of the variable to update.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_variable.yaml
    description: The updated variable
    required: true
  responses:
    '200':
      description: The variable was updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_variable.yaml
    '404':
      description: The account, repository or variable with the given UUID was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
delete:
  tags:
    - Pipelines
  summary: Delete a variable for a repository
  description: Delete a repository level variable.
  operationId: deleteRepositoryPipelineVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: variable_uuid
      description: The UUID of the variable to delete.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The variable was deleted.
    '404':
      description: The account, repository or variable with given UUID was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
