put:
  tags:
    - Pipelines
  description: Update a deployment environment level variable.
  summary: Update a variable for an environment
  operationId: updateDeploymentVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: environment_uuid
      description: The environment.
      required: true
      in: path
      schema:
        type: string
    - name: variable_uuid
      description: The UUID of the variable to update.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/deployment_variable.yaml
    description: The updated deployment variable.
    required: true
  responses:
    '200':
      description: The deployment variable was updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/deployment_variable.yaml
    '404':
      description: >-
        The account, repository, environment or variable with the given UUID was
        not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
delete:
  tags:
    - Pipelines
  description: Delete a deployment environment level variable.
  summary: Delete a variable for an environment
  operationId: deleteDeploymentVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: environment_uuid
      description: The environment.
      required: true
      in: path
      schema:
        type: string
    - name: variable_uuid
      description: The UUID of the variable to delete.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The variable was deleted.
    '404':
      description: >-
        The account, repository, environment or variable with given UUID was not
        found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
