get:
  tags:
    - Pipelines
  summary: Get a known host
  description: Retrieve a repository level known host.
  operationId: getRepositoryPipelineKnownHost
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: known_host_uuid
      description: The UUID of the known host to retrieve.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The known host.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_known_host.yaml
    '404':
      description: >-
        The account, repository or known host with the specified UUID was not
        found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
put:
  tags:
    - Pipelines
  summary: Update a known host
  description: Update a repository level known host.
  operationId: updateRepositoryPipelineKnownHost
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: known_host_uuid
      description: The UUID of the known host to update.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_known_host.yaml
    description: The updated known host.
    required: true
  responses:
    '200':
      description: The known host was updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_known_host.yaml
    '404':
      description: The account, repository or known host with the given UUID was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
delete:
  tags:
    - Pipelines
  summary: Delete a known host
  description: Delete a repository level known host.
  operationId: deleteRepositoryPipelineKnownHost
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: known_host_uuid
      description: The UUID of the known host to delete.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The known host was deleted.
    '404':
      description: The account, repository or known host with given UUID was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
