get:
  tags:
    - Pipelines
  summary: Get SSH key pair
  description: >-
    Retrieve the repository SSH key pair excluding the SSH private key. The
    private key is a write only field and will never be exposed in the logs or
    the REST API.
  operationId: getRepositoryPipelineSshKeyPair
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The SSH key pair.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_ssh_key_pair.yaml
    '404':
      description: The account, repository or SSH key pair was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
put:
  tags:
    - Pipelines
  summary: Update SSH key pair
  description: >-
    Create or update the repository SSH key pair. The private key will be set as
    a default SSH identity in your build container.
  operationId: updateRepositoryPipelineKeyPair
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_ssh_key_pair.yaml
    description: The created or updated SSH key pair.
    required: true
  responses:
    '200':
      description: The SSH key pair was created or updated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_ssh_key_pair.yaml
    '404':
      description: The account, repository or SSH key pair was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
delete:
  tags:
    - Pipelines
  summary: Delete SSH key pair
  description: Delete the repository SSH key pair.
  operationId: deleteRepositoryPipelineKeyPair
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The SSH key pair was deleted.
    '404':
      description: The account, repository or SSH key pair was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
