get:
  tags:
    - Pipelines
  summary: List executions of a schedule
  description: Retrieve the executions of a given schedule.
  operationId: getRepositoryPipelineScheduleExecutions
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: schedule_uuid
      description: The uuid of the schedule.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The list of executions of a schedule.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/paginated_pipeline_schedule_executions.yaml
    '404':
      description: The account or repository was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
