get:
  tags:
    - Deployments
  summary: Get an environment
  description: Retrieve an environment
  operationId: getEnvironmentForRepository
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: environment_uuid
      description: The environment UUID.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The environment.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/deployment_environment.yaml
    '404':
      description: No account, repository or environment with the UUID provided exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
delete:
  tags:
    - Deployments
  description: Delete an environment
  summary: Delete an environment
  operationId: deleteEnvironmentForRepository
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: environment_uuid
      description: The environment UUID.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The environment was deleted.
    '404':
      description: No account or repository with the UUID provided exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
