get:
  tags:
    - Pipelines
  summary: List variables for a repository
  description: Find repository level variables.
  operationId: getRepositoryPipelineVariables
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The retrieved variables.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/paginated_pipeline_variables.yaml
post:
  tags:
    - Pipelines
  summary: Create a variable for a repository
  description: Create a repository level variable.
  operationId: createRepositoryPipelineVariable
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_variable.yaml
    description: The variable to create.
    required: true
  responses:
    '201':
      description: The variable was created.
      headers:
        Location:
          description: The URL of the newly created pipeline variable.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_variable.yaml
    '404':
      description: The account or repository does not exist.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '409':
      description: A variable with the provided key already exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
