delete:
  tags:
    - Repositories
  description: >-
    Deletes the repository user permission between the requested repository and
    user, if one exists.


    Only users with admin permission for the repository may access this
    resource.


    The only authentication method for this endpoint is via app passwords.


    ```

    $ curl -X DELETE
    https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/

    permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a



    HTTP/1.1 204

    ```
  summary: Delete an explicit user permission for a repository
  responses:
    '204':
      description: The repository user permission was deleted and no content returned.
    '401':
      description: The user couldn't be authenticated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '403':
      description: >-
        The requesting user isn't an admin of the repository, or the
        authentication method was not via app password.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '404':
      description: >-
        One or more of the workspace, repository, and user doesn't exist for the
        given identifiers.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
  security:
    - oauth2:
        - repository:admin
    - basic: []
    - api_key: []
get:
  tags:
    - Repositories
  description: >-
    Returns the explicit user permission for a given user and repository.


    Only users with admin permission for the repository may access this
    resource.


    Permissions can be:


    * `admin`

    * `write`

    * `read`

    * `none`


    Example:


    ```

    $ curl
    'https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/
            permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a'

    HTTP/1.1 200

    Location:
    'https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/
               permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a'

    {
        "type": "repository_user_permission",
        "user": {
            "type": "user",
            "display_name": "Colin Cameron",
            "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}",
            "account_id": "557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a"
        },
        "repository": {
            "type": "repository",
            "name": "geordi",
            "full_name": "atlassian_tutorial/geordi",
            "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
        },
        "permission": "admin",
        "links": {
            "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/
                         permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a"
            }
        }
    }

    ```
  summary: Get an explicit user permission for a repository
  responses:
    '200':
      description: Explicit user permission for user and repository
      content:
        application/json:
          schema:
            $ref: ../components/schemas/repository_user_permission.yaml
    '401':
      description: The user couldn't be authenticated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '403':
      description: The requesting user isn't an admin of the repository.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '404':
      description: >-
        One or both of the workspace and repository doesn't exist for the given
        identifiers.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
  security:
    - oauth2:
        - repository:admin
    - basic: []
    - api_key: []
put:
  tags:
    - Repositories
  description: >-
    Updates the explicit user permission for a given user and repository. The
    selected user must be a member of

    the workspace, and cannot be the workspace owner.

    Only users with admin permission for the repository may access this
    resource.


    The only authentication method for this endpoint is via app passwords.


    Permissions can be:


    * `admin`

    * `write`

    * `read`


    Example:


    ```

    $ curl -X PUT -H "Content-Type: application/json"
    'https://api.bitbucket.org/2.0/repositories/

    atlassian_tutorial/geordi/permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a'

    -d         '{
        "permission": "write"
    }'


    HTTP/1.1 200

    Location:
    'https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/

    permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a'



    {
        "type": "repository_user_permission",
        "user": {
            "type": "user",
            "display_name": "Colin Cameron",
            "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}",
            "account_id": "557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a"
        },
        "repository": {
            "type": "repository",
            "name": "geordi",
            "full_name": "atlassian_tutorial/geordi",
            "uuid": "{85d08b4e-571d-44e9-a507-fa476535aa98}"
        },
        "permission": "write",
        "links": {
            "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/atlassian_tutorial/geordi/
                         permissions-config/users/557058:ba8948b2-49da-43a9-9e8b-e7249b8e324a"
            }
        }
    }

    ```
  summary: Update an explicit user permission for a repository
  responses:
    '200':
      description: Explicit user permission updated
      content:
        application/json:
          schema:
            $ref: ../components/schemas/repository_user_permission.yaml
    '400':
      description: >-
        No permission value was provided or the value is invalid (not one of
        read, write, or admin), or the selected user is not a valid user to
        update.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '401':
      description: The user couldn't be authenticated.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '403':
      description: >-
        The requesting user isn't an admin of the repository, or the
        authentication method was not via app password.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '404':
      description: >-
        One or more of the workspace, repo, and selected user doesn't exist for
        the given identifiers.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
  security:
    - oauth2:
        - repository:admin
    - basic: []
    - api_key: []
parameters:
  - name: repo_slug
    in: path
    description: |
      This can either be the repository slug or the UUID of the repository,
      surrounded by curly-braces, for example: `{repository UUID}`.
    required: true
    schema:
      type: string
  - name: selected_user_id
    in: path
    description: >
      This can either be the UUID of the account, surrounded by curly-braces,
      for

      example: `{account UUID}`, OR an Atlassian Account ID.
    required: true
    schema:
      type: string
  - name: workspace
    in: path
    description: |
      This can either be the workspace ID (slug) or the workspace UUID
      surrounded by curly-braces, for example: `{workspace UUID}`.
    required: true
    schema:
      type: string
