get:
  tags:
    - Deployments
  description: Find deployments
  summary: List deployments
  operationId: getDeploymentsForRepository
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The matching deployments.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/paginated_deployments.yaml
