get:
  tags:
    - Pipelines
  summary: List known hosts
  description: Find repository level known hosts.
  operationId: getRepositoryPipelineKnownHosts
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The retrieved known hosts.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/paginated_pipeline_known_hosts.yaml
post:
  tags:
    - Pipelines
  summary: Create a known host
  description: Create a repository level known host.
  operationId: createRepositoryPipelineKnownHost
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_known_host.yaml
    description: The known host to create.
    required: true
  responses:
    '201':
      description: The known host was created.
      headers:
        Location:
          description: The URL of the newly created pipeline known host.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_known_host.yaml
    '404':
      description: The account or repository does not exist.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '409':
      description: A known host with the provided hostname already exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
