put:
  tags:
    - Pipelines
  summary: Update the next build number
  description: >-
    Update the next build number that should be assigned to a pipeline. The next
    build number that will be configured has to be strictly higher than the
    current latest build number for this repository.
  operationId: updateRepositoryBuildNumber
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/pipeline_build_number.yaml
    description: The build number to update.
    required: true
  responses:
    '200':
      description: The build number has been configured.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_build_number.yaml
    '400':
      description: >-
        The update failed because the next number was invalid (it should be
        higher than the current number).
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '404':
      description: The account or repository was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
