delete:
  tags:
    - Pipelines
  summary: Delete a cache
  description: Delete a repository cache.
  operationId: deleteRepositoryPipelineCache
  parameters:
    - name: workspace
      description: The account.
      required: true
      in: path
      schema:
        type: string
    - name: repo_slug
      description: The repository.
      required: true
      in: path
      schema:
        type: string
    - name: cache_uuid
      description: The UUID of the cache to delete.
      required: true
      in: path
      schema:
        type: string
  responses:
    '204':
      description: The cache was deleted.
    '404':
      description: The workspace, repository or cache_uuid with given UUID was not found.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
