get:
  tags:
    - Pipelines
  summary: List variables for a workspace
  description: Find workspace level variables.
  operationId: getPipelineVariablesForWorkspace
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
  responses:
    '200':
      description: The found workspace level variables.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/paginated_pipeline_variables.yaml
post:
  tags:
    - Pipelines
  summary: Create a variable for a workspace
  description: Create a workspace level variable.
  operationId: createPipelineVariableForWorkspace
  parameters:
    - name: workspace
      description: >-
        This can either be the workspace ID (slug) or the workspace UUID
        surrounded by curly-braces, for example `{workspace UUID}`.
      required: true
      in: path
      schema:
        type: string
  requestBody:
    $ref: ../components/requestBodies/pipeline_variable2.yaml
  responses:
    '201':
      description: The created variable.
      headers:
        Location:
          description: The URL of the newly created pipeline variable.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: ../components/schemas/pipeline_variable.yaml
    '404':
      description: The workspace does not exist.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
    '409':
      description: A variable with the provided key already exists.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/error.yaml
